site_name: "de.NBI Cloud Wiki"
docs_dir: wiki
theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/denbi.svg'
  favicon: 'img/denbi.svg'
  custom_dir: wiki/overrides
repo_name: 'deNBI/cloud-user-docs'

repo_url: 'https://github.com/deNBI/cloud-user-docs'
edit_uri: blob/master/wiki/
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
nav:
  - 'Home' : index.md
  - 'Registration' : registration.md
  - 'Citation and publication': citation_and_publication.md
  - 'Portal' :
    - 'Allocation': portal/allocation.md
    - 'Resource/Lifetime Modifications': portal/modification.md
    - 'Project Termination' : portal/termination.md
    - 'Project Overview': portal/project_overview.md
    - 'Profile Page': portal/user_information.md
    - 'Using Vault': portal/vault_user.md
    - 'Cloud Credits': portal/credits.md
    - 'Personal Data': portal/personal_data.md
  - 'Simple VM':
    - simple_vm/index.md
  - 'OpenStack Quickstart' : quickstart.md
  - 'Security' : security.md
  - 'Concept' :
    - 'OpenStack Basics' : Concept/basics.md
    - 'OpenStack Components' : Concept/openstack.md
    - 'Flavors' : Concept/flavors.md
    - 'Images' : Concept/images.md
  - 'Tutorials' :
    - 'Tutorials': Tutorials/index.md
    - 'Access de.NBI Virtual Machines from Windows 10' : Tutorials/Win10_SSH/index.md
    - 'Ansible Automation' : Tutorials/Ansible/index.md
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Hybridcloud' : Tutorials/Hybridcloud/index.md
    - 'Install latest CUDA version' : Tutorials/CUDA/index.md
    - 'Kubermatic' : Tutorials/Kubermatic/index.md
    - 'Loadbalancer' : Tutorials/Loadbalancer/index.md
    - 'Object Storage' : Tutorials/ObjectStorage/index.md
    - 'Reverse Proxy with Elixir AAI': Tutorials/Elixir_AAI/Elixir_AAI.md
    - 'Save FloatingIPs' : Tutorials/SaveFloatingIPs/index.md
    - 'Set up RStudio' : Tutorials/RStudio_Server/index.md
    - 'Persistent SSH Sessions' : Tutorials/Persistent_SSH_Sessions/index.md
    - 'Theia Web IDE': Tutorials/TheiaIde/index.md
    - 'UserData' : Tutorials/UserData/index.md
    - 'Using X2GO': Tutorials/X2GO/x2go.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg Uni' : Compute_Center/Heidelberg.md
    - 'Heidelberg DKFZ' : Compute_Center/Heidelberg-DKFZ.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
    - 'Berlin' : Compute_Center/Berlin.md
    - 'EMBL' : Compute_Center/EMBL.md
  - 'Cloud Admin':
    - 'Project management': cloud_admin/project_management.md
    - 'Configure OpenStack to use Elixir AAI via OpenID Connect': cloud_admin/elixir_OIDC.md
    - 'Register your identity provider for ELIXIR': cloud_admin/identity_provider.md
    - 'News management': cloud_admin/news_management.md
    - 'Vault management': cloud_admin/vault_admin.md

extra_javascript:
  - mathjax.js
  - assets/mathjax/tex-mml-chtml.js

extra:
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/de-nbi/
    name: de.NBI on LinkedIN
  - icon: fontawesome/brands/github
    link: https://github.com/deNBI/
    name: de.NBI on GitHub
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/channel/UCgZ5PU3CyD4c8yxxzJi130g?view_as=subscriber
    name: de.NBI on YouTube
  - icon: fontawesome/brands/wikipedia-w
    link: https://en.wikipedia.org/wiki/German_Network_for_Bioinformatics_Infrastructure
    name: de.NBI on Wikipedia
  footer_links: 
    - { name: "Policies", href: "https://cloud.denbi.de/about/policies/" }
    - { name: "Imprint", href: "https://cloud.denbi.de/about/imprint/" }